# github CI/CD pipeline
name: Test, Build, and Push to Google Cloud run

on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "setup-gcloud"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # github.com/actions/checkout
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install requirements
        run: | # a multiple-line command symbol
          python -m pip install -r requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: | # a multiple-line command symbol
          pytest src/tests.py

  build_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build container image
        run: |
            docker build --platform=linux/amd64 -f Dockerfile -t serverless-py-github .
            docker tag serverless-py-github ${{ secrets.CONTAINER_IMAGE_URL }}:latest
            docker tag serverless-py-github ${{ secrets.CONTAINER_IMAGE_URL }}:${GITHUB_RUN_ID}
            gcloud auth configure-docker us-central1-docker.pkg.dev
            docker push ${{ secrets.CONTAINER_IMAGE_URL }} --all-tags
      - name: Deploy container to Google Cloud run
        run: |
          gcloud run deploy serverless-py-github \
            --image=${{ secrets.CONTAINER_IMAGE_URL }}:${GITHUB_RUN_ID} \
            --allow-unauthenticated \
            --region=${{ secrets.GCLOUD_REGION }} \
            --project=${{ secrets.GCLOUD_PROJECT_ID}}

    # stage:
    #   needs: [test, build_push]
    # deploy: